"""empty message

Revision ID: 4c657868977c
Revises: bd794c84a9d6
Create Date: 2018-11-30 14:24:14.042606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c657868977c'
down_revision = 'bd794c84a9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.drop_constraint('tag_name_key', 'tag', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tag_name_key', 'tag', ['name'])
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    # ### end Alembic commands ###
